### ISSUE TITLE
Update info for auditing students

### ISSUE THREAD

**Issue by firasm** [STAT545-UBC/STAT545-home#10]
Hey @yuliaUU 

Here are some additional information to put about auditing students:

-------------
Auditing students will be: 

1) Graded on a Pass/Fail basis for each assignment/course activity 
2) Exempted from the peer review portion of the course
3) Doing the team project as an individual project (with no other change in scope or requirements)

If you would like to audit the course, you *must* submit the request by 11:59 PM on Thursday March 5th, 2020. After this - without exceptions - students will not be permitted to switch to (or from) audit status.

**Comment by yuliaUU** [comment]
Created a pull request

**Comment by firasm** [comment]
fixed by #12
