### ISSUE TITLE
Invalid PR Template Link

### ISSUE THREAD

**Issue by dy-lin** [STAT545-UBC/STAT545-home#2]
One of the template links on the Peer Review webpage is invalid.

The one on line 66 in `STAT545-home/content/evaluation/peer-review.Rmd` in invalid (the one on line 9 works)

Line 66:
`Use the assignment rubric (above) for ideas about criteria to evaluate and comment on -- we've given you a template to work with [here](https://github.com/STAT545-UBC/Classroom/blob/master/assignments/peer-review-template.md).`

The link should be to the same one on line 9:
https://raw.githubusercontent.com/STAT545-UBC/STAT545-home/master/content/evaluation/peer-review-template.md

**Comment by yuliaUU** [comment]
@dy-lin thanks! Updated!
