### ISSUE TITLE
Update link to discussions and announcements link on home page

### ISSUE THREAD

**Issue by firasm** [STAT545-UBC/STAT545-home#6]
Hi @yuliaUU here is the new link for discussions, announcements, and homework (only one repo): https://github.com/STAT547-UBC-2019-20/Discussions/issues

I think it would be best if we changed this section *just* to have the "discussion and announcements" logo, and remove the hw and announcements section. You can leave the part about emailing the instructor if things should be private.

<img width="1387" alt="Screen Shot 2020-02-13 at 8 17 40 PM" src="https://user-images.githubusercontent.com/2507459/74501105-e65e6780-4e9d-11ea-8623-3b3f0eeeba8c.png">

You can also put the discussion repo link here: 
<img width="519" alt="Screen Shot 2020-02-13 at 8 23 34 PM" src="https://user-images.githubusercontent.com/2507459/74501383-d3986280-4e9e-11ea-9ee8-69ef0808c20c.png">

**Comment by yuliaUU** [comment]
Created the pull request!
